spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:chat
    #    url: jdbc:h2:tcp://localhost:9092/mem:testdb
    #    jdbc-url: jdbc:h2:mem:testdb;
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 1
      maximum-pool-size: 5
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: pool-joo

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
        show_sql: true

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  access_token_expire_time: 1800000
  refresh_token_expire_time: 86400000


logging:
  level:
    org.hibernate.type: debug
